const blogEntries = [

    {
        id: 1,
        link: 'blog-title',
        image: '/blog/blog1/favicon.svg',
        category: 'Technology',
        duration: '3 min read',
        title: '1, How to become a professional bee keeper - for dummies',
        transactionID: 'thisIsAArweaveTransaction ID',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 2,
        link: 'blog-title',
        image: '/blog/blog1/favicon.svg',
        category: 'Technology',
        duration: '3 min read',
        title: '2, How to become a professional bee keeper - for dummies',
        transactionID: 'thisIsAArweaveTransaction ID',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 3,
        link: 'blog-title',
        image: '/blog/blog1/favicon.svg',
        category: 'Technology',
        duration: '3 min read',
        title: '3, How to become a professional bee keeper - for dummies',
        transactionID: 'thisIsAArweaveTransaction ID',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 4,
        link: 'blog-title',
        image: '/blog/blog1/favicon.svg',
        category: 'Announcements',
        duration: '3 min read',
        title: '4, How to become a professional bee keeper - for dummies',
        transactionID: 'thisIsAArweaveTransaction ID',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 5,
        link: 'blog-title',
        image: '/blog/blog1/favicon.svg',
        category: 'Announcements',
        duration: '3 min read',
        title: '5, How to become a professional bee keeper - for dummies',
        transactionID: 'thisIsAArweaveTransaction ID',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 6,
        link: 'blog-title',
        image: '/blog/blog1/favicon.svg',
        category: 'Announcements',
        duration: '3 min read',
        title: '6, How to become a professional bee keeper - for dummies',
        transactionID: 'thisIsAArweaveTransaction ID',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 7,
        link: 'blog-title',
        image: '/blog/blog1/favicon.svg',
        category: 'Announcements',
        duration: '3 min read',
        title: '0, Mind numbingly scalable dApp authentication on Arweave',
        transactionID: 'thisIsAArweaveTransaction ID',
        teaserContent: 'Southern nights Have you ever felt a Southern night? Free as a breeze Not to mention the trees Whistlin tunes that you know and love so Southern nights Just as good even when you close your eyes...',
        content: 'Because hes oooo soo good and hes oohhhh so fine and hes ohhh so healthy in his body and his mind.',
      },

  ];
  
  export default blogEntries;
  