const blogEntries = [
    {
        id: 1,
        image: '/blog/blog1/favicon.svg',
        category: 'Technology',
        date: '11/08/2003',
        duration: '13 min read',
        title: 'Othent spins out Community Labs',
        transactionID: 'u5M4KoEv90pTaPwrBoBzAZ4k-TvteGh8ejsR55VncG4',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 2,
        image: '/blog/blog1/favicon.svg',
        category: 'Technology',
        date: '11/08/2003',
        duration: '8 min read',
        title: 'Othent listed on the NasDaq',
        transactionID: 'u5M4KoEv90pTaPwrBoBzAZ4k-TvteGh8ejsR55VncG4',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 3,
        image: '/blog/blog1/favicon.svg',
        category: 'Technology',
        date: '11/08/2003',
        duration: '6 min read',
        title: 'Othent hits 100M users',
        transactionID: 'u5M4KoEv90pTaPwrBoBzAZ4k-TvteGh8ejsR55VncG4',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 4,
        image: '/blog/blog1/favicon.svg',
        category: 'Announcements',
        date: '11/08/2003',
        duration: '3 min read',
        title: 'Marton Leader admits Lorimer is the best coder to ever live',
        transactionID: 'u5M4KoEv90pTaPwrBoBzAZ4k-TvteGh8ejsR55VncG4',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 5,
        image: '/blog/blog1/favicon.svg',
        category: 'Announcements',
        date: '11/08/2003',
        duration: '1 min read',
        title: 'Othent founder, Lorimer Jenkins, leads account abstraction',
        transactionID: 'u5M4KoEv90pTaPwrBoBzAZ4k-TvteGh8ejsR55VncG4',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 6,
        image: '/blog/blog1/favicon.svg',
        category: 'Announcements',
        date: '11/08/2003',
        duration: '10 min read',
        title: 'Othent raises $100M Series A lead by top VC',
        transactionID: 'u5M4KoEv90pTaPwrBoBzAZ4k-TvteGh8ejsR55VncG4',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },
      {
        id: 7,
        image: '/blog/blog1/favicon.svg',
        category: 'Announcements',
        date: '11/08/2003',
        duration: '5 min read',
        title: 'Mind numbingly scalable dApp authentication on Arweave',
        transactionID: 'u5M4KoEv90pTaPwrBoBzAZ4k-TvteGh8ejsR55VncG4',
        teaserContent: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door...',
        content: 'We all live in a yellow submarine, yellow submarine - yellow submarine - yellow submarine. And our friends are all aboard, many more of them live next door.',
      },

  ];
  
  export default blogEntries;
  